#!/bin/sh -eu

cd "$(dirname "$0")"

__dotfiles_repo__build_filename="./$(basename "$0")"

while [ -L "$__dotfiles_repo__build_filename" ]; do
  __dotfiles_repo__build_filename="$(readlink "$__dotfiles_repo__build_filename")"

  cd "$(dirname "$__dotfiles_repo__build_filename")"

  __dotfiles_repo__build_filename="./$(basename "$__dotfiles_repo__build_filename")"
done

unset -v '__dotfiles_repo__build_filename'

cd '..'

[ "$PWD" != "$(pwd -P)" ] && cd "$(pwd -P)"

"$PWD/libexec/clean" > '/dev/null' 2>&1

cp -R "$PWD/src" "$PWD/build"
