#!/bin/sh -u

cd "$(dirname "$0")"

__dotfiles_repo__clean_filename="./$(basename "$0")"

while [ -L "$__dotfiles_repo__clean_filename" ]; do
  __dotfiles_repo__clean_filename="$(readlink "$__dotfiles_repo__clean_filename")"

  cd "$(dirname "$__dotfiles_repo__clean_filename")"

  __dotfiles_repo__clean_filename="./$(basename "$__dotfiles_repo__clean_filename")"
done

unset -v '__dotfiles_repo__clean_filename'

cd '..'

[ "$PWD" != "$(pwd -P)" ] && cd "$(pwd -P)"

printf 'Removing build directory ... '

rm -fr "$PWD/build" > '/dev/null' 2>&1

__dotfiles_repo__clean_rm_exit_status=$?

if [ $__dotfiles_repo__clean_rm_exit_status -eq 0 ]; then
  echo 'succeeded.'

  unset -v '__dotfiles_repo__clean_rm_exit_status'
else
  echo 'failed.'

  exit $__dotfiles_repo__clean_rm_exit_status
fi
