#!/bin/sh -eu
#
# Determine and print the lowercased host OS name

readonly EXPECTED_OS_LIST="$(cat <<EOF
android darwin dragonfly freebsd linux netbsd openbsd plan9 solaris windows
EOF
)"

readonly RECEIVED_OS="$(
  uname \
    | tr '[:upper:]' '[:lower:]' \
    | sed 's/mingw/windows/; s/.*windows.*/windows/'
)"

if [ "${EXPECTED_OS_LIST#*"$RECEIVED_OS"}" = "$EXPECTED_OS_LIST" ]; then
  echo 'unix'
else
  echo "$RECEIVED_OS"
fi
