#!/bin/sh -eu
#
# Generate a static host-specific environment file
#
# @SYNOPSIS
#   `generate-env-file`
#
# @DESCRIPTION
#   The _generate-env-file_ script shall generate a static configuration file
#   that exports variables specifying the constant environment settings for the
#   dotfiles CLI app depending on the current host system.
#
# @OPTIONS
#   None.
#
# @OPERANDS
#   None.
#
# @STDIN
#   Not used.
#
# @INPUT_FILES
#   None.
#
# @ENVIRONMENT_VARIABLES
#   `$PWD` - TODO
#
# @ASYNCHRONOUS_EVENTS
#   Default.
#
# @STDOUT
#   Not used.
#
# @STDERR
#   The standard error shall be used only for diagnostic messages.
#
# @OUTPUT_FILES
#   The output file shall be TODO
#
# @EXTENDED_DESCRIPTION
#   None.
#
# @EXIT_STATUS
#   `0`  - The environment file was generated successfully.
#   `>0` - An error occurred.
#
# @CONSEQUENCES_OF_ERRORS
#   The environment file shall not be generated.
#

readonly DOTFILES_DIR="$PWD"
readonly DOTFILES_OPT_DIR="$DOTFILES_DIR/opt"
readonly DOTFILES_PROVIDER='dotfiles.christiangrete.com'
readonly DOTFILES_CLI_DIR="$DOTFILES_OPT_DIR/$DOTFILES_PROVIDER/cli"
readonly DOTFILES_CLI_BIN_DIR="$DOTFILES_CLI_DIR/bin"
readonly DOTFILES_CLI_SCPT_FILE="$DOTFILES_CLI_BIN_DIR/dotfiles"
readonly DOTFILES_REPO_DIR="$(dirname "$DOTFILES_DIR")"

#
# TODO: Determine host OS
#

dotfiles_os="$(uname | tr '[:upper:]' '[:lower:]' | sed 's/mingw/windows/; s/.*windows.*/windows/')"

#
# TODO: Determine host arch
#

dotfiles_arch=''

if [ "$dotfiles_os" = 'darwin' ]; then
  # TODO:
  # if sysctl machdep.cpu.extfeatures | grep EM64T >/dev/null; then
  #   echo amd64
  # else
  #   uname -m | sed 's/i386/386/'
  # fi
  dotfiles_arch=''
else
  dotfiles_arch="$(uname -m | sed 's/^..86$$/386/; s/^.86$$/386/; s/x86_64/amd64/; s/arm.*/arm/')"
fi

#
# TODO: Determine CLI bin file
#

dotfiles_cli_bin_file="$DOTFILES_CLI_SCPT_FILE"

if [ -n "$dotfiles_os" -a -n "$dotfiles_arch" ]; then
  dotfiles_cli_bin_file="$dotfiles_cli_bin_file-$dotfiles_os-$dotfiles_arch"
fi

[ ! -d './var/etc' ] && mkdir -p './var/etc'

echo "$(cat <<EOF
#
# Auto generated file
#

export DOTFILES_ARCH='$dotfiles_arch'
export DOTFILES_CLI_BIN_DIR='$DOTFILES_CLI_BIN_DIR'
export DOTFILES_CLI_BIN_FILE='$dotfiles_cli_bin_file'
export DOTFILES_CLI_DIR='$DOTFILES_CLI_DIR'
export DOTFILES_CLI_SCPT_FILE='$DOTFILES_CLI_SCPT_FILE'
export DOTFILES_DIR='$DOTFILES_DIR'
export DOTFILES_OPT_DIR='DOTFILES_OPT_DIR'
export DOTFILES_OS='$dotfiles_os'
export DOTFILES_PROVIDER='$DOTFILES_PROVIDER'
export DOTFILES_REPO_DIR='$DOTFILES_REPO_DIR'
EOF
)" > './var/etc/environment.sh'
