#!/bin/sh -eu
#
# Generate a static host-specific environment file
#
# @SYNOPSIS
#   `generate-env-file`
#
# @DESCRIPTION
#   The _generate-env-file_ script shall generate a static configuration file
#   that exports variables specifying the constant environment settings for the
#   dotfiles CLI app depending on the current host system.
#
# @OPTIONS
#   None.
#
# @OPERANDS
#   None.
#
# @STDIN
#   Not used.
#
# @INPUT_FILES
#   None.
#
# @ENVIRONMENT_VARIABLES
#   `$PWD` - TODO
#
# @ASYNCHRONOUS_EVENTS
#   Default.
#
# @STDOUT
#   Not used.
#
# @STDERR
#   The standard error shall be used only for diagnostic messages.
#
# @OUTPUT_FILES
#   The output file shall be TODO
#
# @EXTENDED_DESCRIPTION
#   None.
#
# @EXIT_STATUS
#   `0`  - The environment file was generated successfully.
#   `>0` - An error occurred.
#
# @CONSEQUENCES_OF_ERRORS
#   The environment file shall not be generated.
#

readonly DOTFILES_DIR="$PWD"
readonly DOTFILES_OPT_DIR="$DOTFILES_DIR/opt"
readonly DOTFILES_OS="$(command './libexec/determine-os')"
readonly DOTFILES_PROVIDER='dotfiles.christiangrete.com'
readonly DOTFILES_CLI_DIR="$DOTFILES_OPT_DIR/$DOTFILES_PROVIDER/cli"
readonly DOTFILES_CLI_BIN_DIR="$DOTFILES_CLI_DIR/bin"
readonly DOTFILES_CLI_SCPT_FILE="$DOTFILES_CLI_BIN_DIR/dotfiles"
readonly DOTFILES_REPO_DIR="$(dirname "$DOTFILES_DIR")"

#
# TODO: Determine host arch
#

if [ "$DOTFILES_OS" = 'darwin' ]; then
  DOTFILES_ARCH="$(command './libexec/determine-darwin-arch')"
else
  DOTFILES_ARCH="$(command './libexec/determine-arch')"
fi

readonly DOTFILES_ARCH

#
# TODO: Determine CLI bin file
#

dotfiles_cli_bin_file="$DOTFILES_CLI_SCPT_FILE"

if [ -n "$DOTFILES_OS" -a -n "$DOTFILES_ARCH" ]; then
  dotfiles_cli_bin_file="$dotfiles_cli_bin_file-$DOTFILES_OS-$DOTFILES_ARCH"
fi

[ ! -d './var/etc' ] && mkdir -p './var/etc'

echo "$(cat <<EOF
#
# Auto generated file
#

export DOTFILES_ARCH='$DOTFILES_ARCH'
export DOTFILES_CLI_BIN_DIR='$DOTFILES_CLI_BIN_DIR'
export DOTFILES_CLI_BIN_FILE='$dotfiles_cli_bin_file'
export DOTFILES_CLI_DIR='$DOTFILES_CLI_DIR'
export DOTFILES_CLI_SCPT_FILE='$DOTFILES_CLI_SCPT_FILE'
export DOTFILES_DIR='$DOTFILES_DIR'
export DOTFILES_OPT_DIR='DOTFILES_OPT_DIR'
export DOTFILES_OS='$DOTFILES_OS'
export DOTFILES_PROVIDER='$DOTFILES_PROVIDER'
export DOTFILES_REPO_DIR='$DOTFILES_REPO_DIR'
EOF
)" > './var/etc/environment.sh'
